<?php

namespace AppBundle\Repository;

/**
 * CoachesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachesRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectCoachByCountry($country, $name)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c.name, c.age, c.biography FROM AppBundle:Coaches c JOIN c.team t
     WHERE t.country = :country AND c.name = :name')
            ->setParameter('country', $country)
            ->setParameter('name', $name)
            ->setMaxResults(1)->getOneOrNullResult();
    }
}
