<?php

namespace AppBundle\Repository;

/**
 * PlayersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayersRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectPlayerByCountry($country, $name)
    {
        return $this->createQueryBuilder('p')
            ->select('p.name', 'p.age', 'p.biography')
            ->join('p.team', 'team')
            ->where('team.country = :country', 'p.name = :name')
            ->setParameter('country', $country)
            ->setParameter('name', $name)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
